name: euroscipy-astro
channels:
  - conda-forge
  - dsdale24
dependencies:
  - python=3.6
  - pip
  - cmake
  - astropy
  - jupyter
  - matplotlib
  - numpy
  - pyqtgraph
  - pyqt5
  - pip:
    - modopt
    - sf_tools
    - git+https://github.com/CEA-COSMIC/pysap
